### ISSUE TITLE
Is this rep alive?

### ISSUE THREAD

**Issue by dr-dimitru** [simplresty/ngx_mongo#6]
1. Is this repository alive?
2. Any plans for future development?
3. Support for nginx@1.10.*?

**Comment by simpl** [comment]
Hi,

Thanks for your interest in this module.

The honest answer us that no, it's not really alive and hasn't been for a long time. We generally use nginx/lua, esp. OpenResty now, and prefer Couchbase over MongoDB, so it's no longer a focus.

Future dev of this module is not really on the cards, at least from my perspective, including making it work.with newer versions of Nginx, unless it's easy, and I don't have time to look into it right now.

Sorry.

**Comment by dr-dimitru** [comment]
@simpl thank you for the reply, got it.

**Comment by simpl** [comment]
@dr-dimitru 

I have re-opened this issue because after a long period of relative inactivity on Github, I'm going to get back into it again.  Although I don't actively use this module myself right now, at some stage hopefully in the next couple of months, I shall try to dedicate some time to getting it working on all versions of Nginx that would not require huge modifications.

I'm afraid I can't give you a definite timeframe, because I have a lot of things to do right now that need to take priority, but you can now consider it on my 'todo list'.

When I'm working on this module again, I'll get back in touch, and if you're still interested, any feedback on testing would be greatly appreciated.

Thanks.

**Comment by renatop7** [comment]
Hi, I have an interest too in this module.

I tried to add it to nginx but I get the error:
"ngx_mongo only works only on little endian platforms"

Is this because of nginx version?

**Comment by Maccaday** [comment]
@renatop7 your issue is different to this issue.  I shall open a new issue, and post the response there.

**Comment by dr-dimitru** [comment]
OP is solved, project actively maintained, closing this thread.
